### PR TITLE
added carousels for sample images

### PR DESCRIPTION
**Pull request by rohanD11**
Review the carousel

### CODE REVIEW

**Review by ashwin-acharya01 — COMMENTED** [review]
@rohanD11 Please Add some sample images so I could verify

**Comment by rohanD11** [comment]
Already added three sample images...

**Comment by ashwin-acharya01** [comment]
Could you add screenshots of the carousel here? It would help me to review the changes.

**Comment by rohanD11** [comment]
Screenshot 2023-09-17 184024

**Comment by Abhijeet-Bhushari** [comment]
@rohanD11 keep 3 images at a time for desktop view and 1 for mobile version. Also you can make the carousel auto sliding which stops at hover.

**Pull request closed without merging**
